### ISSUE TITLE
Names with maximal length in TD1 will miss their last character.

### ISSUE THREAD

**Issue by rbrouwer** [Mattijah/QKMRZParser#4]
Names with maximal length in TD1 will miss their last character.

https://github.com/Mattijah/QKMRZParser/blob/2e41b09f724373167cbca515b182908be4b6cfbe/QKMRZParser/Parsers/Parser%2BTD1.swift#L36

Length is 29, but should be 30.

**Comment by Mattijah** [comment]
Thanks for the bug report! Resolved here: https://github.com/Mattijah/QKMRZParser/commit/9c30294632dc000eb6ab74a445d01c10238d1cac
